REGISTER HashUDF.jar;

inputfile = load '/user/hadoop/test.csv' USING PigStorage(',') as (SAFETYREPORTVERSION:chararray,SAFETYREPORTID:chararray,PRIMARYSOURCECOUNTRY:chararray,OCCURCOUNTRY:chararray,TRANSMISSIONDATEFORMAT:chararray,TRANSMISSIONDATE:chararray,REPORTTYPE:chararray,RECEIVEDATEFORMAT:chararray,RECEIVEDATE:chararray,RECEIPTDATEFORMAT:chararray,RECEIPTDATE:chararray,FULFILLEXPEDITECRITERIA:chararray,COMPANYNUMB:chararray,DUPLICATE:chararray,DUPLICATESOURCE:chararray,DUPLICATENUMB:chararray,REPORTERCOUNTRY:chararray,QUALIFICATION:chararray,SENDERTYPE:chararray,SENDERORGANIZATION:chararray,RECEIVERTYPE:chararray,RECEIVERORGANIZATION:chararray,PATIENTONSETAGE:int,PATIENTONSETAGEUNIT:chararray,PATIENTWEIGHT:int,PATIENTSEX:chararray,DRUGCHARACTERIZATION:chararray,MEDICINALPRODUCT:chararray,DRUGDOSAGETEXT:chararray,DRUGDOSAGEFORM:chararray,DRUGAUTHORIZATIONNUMB:chararray,DRUGSTRUCTUREDOSAGENUMB:chararray,DRUGSTRUCTUREDOSAGEUNIT:chararray,DRUGSEPARATEDOSAGENUMB:chararray,DRUGINTERVALDOSAGEUNITNUMB:chararray,DRUGINTERVALDOSAGEDEFINITION:chararray,DRUGAADMINISTRATIONROUTE:chararray,DRUGINDICATION:chararray,DRUGSTARTDATEFORMAT:chararray,DRUGSTARTDATE:chararray,DRUGENDDATEFORMAT:chararray,DRUGENDDATE:chararray,ACTIONDRUG:chararray,ACTIVESUBSTANCENAME:chararray,REACTIONMEDDRAVERSIONPT:chararray,REACTIONMEDDRAPT:chararray,REACTIONOUTCOME:chararray,NARRATIVEINCLUDECLINICAL:chararray);

notnulldrugsubstances = FILTER inputfile by ACTIVESUBSTANCENAME is not null OR ACTIVESUBSTANCENAME != '';

drugsubstances = foreach notnulldrugsubstances generate com.tpgsi.pigudf.StringHashCode(ACTIVESUBSTANCENAME),ACTIVESUBSTANCENAME;

drugsubstance = DISTINCT drugsubstances;

STORE drugsubstance INTO 'drugsubstance' USING PigStorage (',');